CREATE TABLE IF NOT EXISTS porter_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    market_id INT,
    created_at DATETIME,
    actual_delivery_time DATETIME,
    store_primary_category VARCHAR(255),
    order_protocol INT,
    total_items INT,
    subtotal FLOAT,
    num_distinct_items INT,
    min_item_price FLOAT,
    max_item_price FLOAT,
    total_onshift_dashers INT,
    total_busy_dashers INT,
    total_outstanding_orders INT,
    estimated_store_to_consumer_driving_duration INT,
    delivery_duration_mins INT,
    avg_item_price FLOAT,
    dasher_utilization FLOAT,
    orders_per_dasher FLOAT,
    order_date DATE,
    order_hour INT,
    day_of_week VARCHAR(20)
);
